server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

websocketClientConfiguration:
  serverHost: ws://docker.for.mac.localhost:9999
  clientHost: http://192.168.43.215:9998
  threadPoolSize: 5 # 5 threads
  initialDelay: 30 # 0 seconds delay on startup
  period: 30 #seconds
